from apps.home_app import HomeApp
from apps.my_loading_app import MyLoadingApp
from apps.true_range_app import TrueRangeApp
from apps.data_app import DataApp
from apps.highest_hour_in_day_app import HighestHourInDayApp
from apps.diff_data_app import DiffDataApp
from apps.data2h_app import Data2hApp
from apps.mid_autumn_app import MidAutumnApp
from apps.morning_session import MorningSession
from apps.inside_and_outside_app import InsideAndOutsideApp
from apps.month_return_app import MonthReturnApp
